### ISSUE TITLE
Permission level

### ISSUE THREAD

**Issue by Foxite** [rmnaderdev/Whitelist-Sync-2#15]
I noticed that the model does not keep track of the permission level of an opped player. As an example, my server has two ops, myself and some other person I recruited. I have level 4, and they have level 3; the only difference between us is that they cannot use `/stop`, but this is still an important distinction to make.

I propose adding `int permissionLevel` to OppedPlayer. As for migrating existing databases, I suggest that if the permissionLevel column is missing from the table, we assume that every player in the list is op level 4. The column is added either automatically or using a command.

I could probably do this myself but I decided to open an issue first, so we can discuss it some more.

**Comment by PotatoSauceVFX** [comment]
@Foxite As a matter of fact, this mod used to track that property for ops. I can't remember why I removed it. It should be simple to re-add. That would be something to include in the refactor mentioned in #16.

**Comment by rmnaderdev** [comment]
Added this feature to the list of todos. Closing this ticket.
