### ISSUE TITLE
Sync ban list // refactor proposal

### ISSUE THREAD

**Issue by Foxite** [rmnaderdev/Whitelist-Sync-2#16]
We currently sync the whitelist and the list of opped players. There is one more player list that we could sync, which is the ban list.

I think in order to sync banlists we can pretty much duplicate the existing code for whitelists. However, at that point we would be violating the DRY principle, as we have three components that are largely the same; the banlist, whitelist, and oplist can be refactored into a single component with three instances. I'm thinking of something like this:

```java
// owns a BaseService instance, and can add, remove, and read. We keep three instances of this class, one for each of the implementations of SyncedPlayer.
public abstract class SyncedPlayerList<TPlayer extends SyncedPlayer> { ... }

public abstract class SyncedPlayer { ... } // uuid, name
public class WhitelistedPlayer extends SyncedPlayer { ... } // isWhitelisted
public class BannedPlayer extends SyncedPlayer { ... } // isBanned
public class OppedPlayer extends SyncedPlayer { ... } // isOpped or permissionLevel (see #15)
```

And BaseService could be modified so that it only allows to retrieve the entire list, and add/remove entries. Implementations of BaseService would be responsible for determining how to store the entries using reflection. Perhaps most of this logic could be placed in a single utility class, or in BaseService if we make it an abstract class instead of an interface.

Such a change would be far too significant for me to implement without some discussion. What do you think?

**Comment by PotatoSauceVFX** [comment]
@Foxite Thank you for the suggestion. I would love to discuss this further. Whitelist Sync could use a complete restructure as I have learned a lot more as a developer since I wrote it. When I have some time to work on this mod, I will reach out to discuss.

**Comment by sauramel** [comment]
Dont suppose this is happening any time soon?

**Comment by PotatoDotJar** [comment]
@sauramel I do not plan to do a refactor anytime soon and I don't plan to add ban list syncing.

**Comment by rmnaderdev** [comment]
Added this to the list of todos. I am thinking it will be a feature in v1.5.X or 1.6. Closing this issue.
