### ISSUE TITLE
Server exception on startup using whitelistsync2-1.16.5-2.2.5.jar

### ISSUE THREAD

**Issue by cauliflower69** [rmnaderdev/Whitelist-Sync-2#22]
https://pastebin.com/WEiN1buc

I was testing it on a local host with an established whitelist to try and get the mod to work on our servers and ran into an issue. 

Any help would be greatly appreciated.

**Comment by PotatoSauceVFX** [comment]
@cauliflower69 Thanks for the report. Does this always happen on startup?

**Comment by PotatoSauceVFX** [comment]
This is a common error and does not cause a crash as far as I know. I have looked into what is causing it and I could not figure it out. For now it seems harmless. Please let me know if it causes the server not to start, otherwise I will keep this issue open until I remove the error.

**Comment by cauliflower69** [comment]
It doesn't prevent the server from starting

**Comment by PotatoSauceVFX** [comment]
Yeah. I spent a day or two trying to figure out why this is happening. It has something to do with the sync thread and SQLite, but I can't figure it out. It is a low priority since it is not preventing things from working as far as I can tell. Any help from others is appreciated.

**Comment by PotatoSauceVFX** [comment]
Never mind, this issue still persists in 2.3.2. I have put well over 3 days into this. Everything should work with this error. Just ignore it for now.
