### ISSUE TITLE
Is name-based whitelist feature supported?

### ISSUE THREAD

**Issue by yqs112358** [rmnaderdev/Whitelist-Sync-2#32]
Hello, I am wondering that is Whitelist-Sync-2 compatible with [EasyWhitelist](https://github.com/NikitaCartes/EasyWhitelist), which changes the behavior of whitelist (banlist / op-list) from uuid-based to name-based, allowing it to be use at offline mode.

**Comment by rmnaderdev** [comment]
I am not sure if it is compatible, but I do know that Whitelist Sync requires online mode and uses the UUIDs so I would not expect it to work in offline mode.

**Comment by yqs112358** [comment]
Oh, it is interesting that I have tested `Whitelist-Sync-2` on my online-offline mixed servers, and it seems to be working. Mixed online verify provided by EasyWhitelist is not affected.

And... the last question ☺️ is it true that even if I don't use `/wl add` command to add whitelist for players (use the command provided by EasyWhitelist), Writelist-Sync-2 will still automatically read and update it to the database every 60 seconds?

**Comment by rmnaderdev** [comment]
To answer your last question: as of v2.8.0 of the mod, there are no more /wl commands specific to managing the player lists. Whitelist Sync intercepts the normal vanilla commands to manage the whitelists, ops, banned players, and banned ips.

**Comment by yqs112358** [comment]
ok, thanks so much🥰
